### ISSUE TITLE
unclear visit_str error

### ISSUE THREAD

**Issue by softprops** [frostly/serializable_enum#1]
I was happy to find your crate as it seems to solve exactly the problem I had when switching a project over from rustc-serialize to serde. Following you're instructions I ran into a curious error about a missing `visit_str`. I'm not sure if it's something that should be synthesized not being synthesized or just me not implementing something that's not documented.

Here's an example of my current code followed by an error in my build output. Can you see what I'm doing wrong?

``` rust
serializable_enum! {
    /// representation of deployment and commit status states
    pub enum StatusState {
        /// pending
        Pending,
        /// success
        Success,
        /// error
        Error,
        /// failure
        Failure,
    }
    StatusStateVisitor
}

impl_as_ref_from_str! {
    StatusState {
        Pending => "pending",
        Success => "success",
        Error => "error",
        Failure => "failure",
    }
    Error::Parse
}
```

```
<serializable_enum macros>:20:15: 20:39 error: no method named `visit_str` found for type `&mut D` in the current scope
<serializable_enum macros>:20 deserializer . visit_str ( $ visitor ) } } )
                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/source/target/debug/build/hubcaps-6dce4f3a1fc69f34/out/rep.rs:4:1: 10:54 note: in this expansion of serializable_enum! (defined in <serializable_enum macros>)
src/rep.rs:14:1: 14:47 note: in this expansion of include!
<serializable_enum macros>:20:15: 20:39 help: items from traits can only be used if the trait is implemented and in scope; the following traits define an item `visit_str`, perhaps you need to implement one of them:
<serializable_enum macros>:20:15: 20:39 help: candidate #1: `serde::de::Deserializer`
<serializable_enum macros>:20:15: 20:39 help: candidate #2: `serde::de::Visitor`
<serializable_enum macros>:20:15: 20:39 help: candidate #3: `serde::ser::Serializer`
<serializable_enum macros>:20:15: 20:39 help: candidate #4: `serde::de::Visitor`
```

**Comment by softprops** [comment]
Note it looks like there would be some synthesize of this method by the name passed to the macro after the enum declaration, in my case `StatusStateVisitor`. Is this something I need to implement explicitly?

**Comment by softprops** [comment]
user error. I was using 0.1, I upgraded to 0.3 and that seemed to fix my issue. fantastic crate. this seems to unblock the one issue I had with serde after transitioning over from rustc serialize

**Comment by compressed** [comment]
Great, glad it worked well for you! I had to release v0.3.0 to support the new serde version (0.7.0) so that's why it wasn't working with the older version.
